# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 02:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseNumber', models.CharField(max_length=50)),
                ('courseName', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=6)),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('courseMaterialID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='assignment', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('examID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('courseID', models.ForeignKey(db_column='courseID', on_delete=django.db.models.deletion.DO_NOTHING, to='API.Course')),
            ],
        ),
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('fileID', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2000)),
                ('label', models.CharField(max_length=50)),
                ('assocCourseMaterialID', models.ForeignKey(db_column='assocCourseMaterialID', null=True, on_delete=django.db.models.deletion.CASCADE, to='API.CourseMaterial')),
            ],
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='assocExamID',
            field=models.ForeignKey(db_column='assocExamID', null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Exam'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='courseID',
            field=models.ForeignKey(db_column='courseID', on_delete=django.db.models.deletion.DO_NOTHING, to='API.Course'),
        ),
    ]
