-- MySQL Script generated by MySQL Workbench
-- Sat Aug 26 16:50:04 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `courseID` INT NOT NULL,
  `courseNumber` VARCHAR(45) NULL,
  `courseName` VARCHAR(45) NULL,
  `instructor` VARCHAR(45) NULL,
  `color` VARCHAR(6) NULL,
  `assocUserID` INT NULL,
  PRIMARY KEY (`courseID`),
  INDEX `userID_idx` (`assocUserID` ASC),
  CONSTRAINT `userID`
    FOREIGN KEY (`assocUserID`)
    REFERENCES `mydb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exam` (
  `examID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `assocCourseID` INT NULL,
  PRIMARY KEY (`examID`),
  INDEX `courseID_idx` (`assocCourseID` ASC),
  CONSTRAINT `courseID`
    FOREIGN KEY (`assocCourseID`)
    REFERENCES `mydb`.`Course` (`courseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assignment` (
  `assignmentID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `assocExamID` INT NOT NULL,
  `assocCourseID` INT NULL,
  PRIMARY KEY (`assignmentID`),
  INDEX `courseID_idx` (`assocCourseID` ASC),
  CONSTRAINT `courseID`
    FOREIGN KEY (`assocCourseID`)
    REFERENCES `mydb`.`Course` (`courseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Note` (
  `noteID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `assocExamID` INT NOT NULL,
  `assocCourseID` INT NULL,
  PRIMARY KEY (`noteID`),
  INDEX `courseID_idx` (`assocCourseID` ASC),
  CONSTRAINT `courseID`
    FOREIGN KEY (`assocCourseID`)
    REFERENCES `mydb`.`Course` (`courseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
